import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button"
import {
  ClerkProvider,
  // SignInButton,
  // SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import Link from "next/link";
import Image from "next/image";
import Sidebar from "@/components/Sidebar";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <nav className='flex justify-between h-18 items-center bg-black text-white'>
            <div className = 'flex mx-0 items-center'>
              {/* <div className ='flex items-center'>Logo</div> */}
              {/* <div className="text-3xl">UTILIX</div> */}
              <Image
                src="/assets/logo.svg" // path is relative to public/
                alt="Company Logo"
                width={250}
                height={250}
                className="rounded-full object-contain"
              />
            </div>

            <div className=''>

            <SignedOut>
            <Button className="mx-3">
              <Link href='/signup'>
              Sign Up
              </Link>
            </Button>
            <Button className='mx-3' >
              <Link href='/signin'>
              Sign In
              </Link>
            </Button>
            </SignedOut>

            <SignedIn>
              <div className='mr-8 felx items-center'>
                <UserButton/>
              </div>
            </SignedIn>
            </div>
          </nav>
          <div className='flex'>

          <Sidebar></Sidebar>
          {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
